// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateImageTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateImageTask'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectTasks(arg1) {
  return window['go']['main']['App']['GetProjectTasks'](arg1);
}

export function GetResizedImageData(arg1) {
  return window['go']['main']['App']['GetResizedImageData'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2, arg3);
}

export function SaveUploadedFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveUploadedFile'](arg1, arg2, arg3);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
