// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function CreateImageTask(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<models.ImageTask>;

export function CreateProject(arg1:string,arg2:string):Promise<models.Project>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetImageData(arg1:string):Promise<string>;

export function GetProject(arg1:number):Promise<models.Project>;

export function GetProjectTasks(arg1:number):Promise<Array<models.ImageTask>>;

export function GetResizedImageData(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<models.Project>>;

export function Login(arg1:string,arg2:string):Promise<services.LoginResponse>;

export function MessageDialog(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveUploadedFile(arg1:number,arg2:Array<number>,arg3:string):Promise<string>;

export function UpdateProject(arg1:models.Project):Promise<void>;
